### ISSUE TITLE
IM Event Set Calculator fails with background seismicity and UCERF3

### ISSUE THREAD

**Issue by kevinmilner** [opensha/opensha#14]
The following exception is raised in the IM event set calculator if you try to enable background seismicity with UCERF3

```
kevin@steel:/tmp/im_event$ java -jar IM_EventSetCalc_v3_0_ASCII.jar ExampleInputFile_v3_0_ASCII.txt test_out --d
May 17, 2021 2:09:44 PM org.opensha.sha.calc.IM_EventSet.v03.IM_EventSetCalc_v3_0_ASCII parseFile
INFO: Parsing input file: ExampleInputFile_v3_0_ASCII.txt
May 17, 2021 2:09:44 PM org.opensha.sha.calc.IM_EventSet.v03.IM_EventSetCalc_v3_0_ASCII getERF
CONFIG: Attempting to identify ERF from name: Mean UCERF3 FM3.1
May 17, 2021 2:09:44 PM org.opensha.sha.calc.IM_EventSet.v03.IM_EventSetCalc_v3_0_ASCII createMeanUCERF3_Forecast
CONFIG: Creating MeanUCERF3 ERF
MeanUCERF3 store dir: /home/kevin/.opensha/ucerf3_erf
May 17, 2021 2:09:44 PM sun.awt.X11.XToolkit setBackingStoreType
CONFIG: The system property sun.awt.backingStore is not set, by default backingStore=NotUseful
loading rake basis for: Def. Model Mean
loading rake basis for: Def. Model Mean
May 17, 2021 2:09:45 PM org.opensha.sha.calc.IM_EventSet.v03.IM_EventSetCalc_v3_0_ASCII createMeanUCERF3_Forecast
CONFIG: MeanUCERF3 Preset: FM3_1_BRANCH_AVG
May 17, 2021 2:09:45 PM org.opensha.sha.calc.IM_EventSet.v03.IM_EventSetCalc_v3_0_ASCII main
INFO: Error parsing input file!
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Enum (java.lang.String and java.lang.Enum are in module java.base of loader 'bootstrap')
	at org.opensha.commons.param.constraint.impl.EnumConstraint.isAllowed(EnumConstraint.java:24)
	at org.opensha.commons.param.AbstractParameter.isAllowed(AbstractParameter.java:181)
	at org.opensha.commons.param.AbstractParameter.setValue(AbstractParameter.java:198)
	at org.opensha.sha.calc.IM_EventSet.v03.IM_EventSetCalc_v3_0_ASCII.toApplyBackGroud(IM_EventSetCalc_v3_0_ASCII.java:519)
	at org.opensha.sha.calc.IM_EventSet.v03.IM_EventSetCalc_v3_0_ASCII.parseFile(IM_EventSetCalc_v3_0_ASCII.java:217)
	at org.opensha.sha.calc.IM_EventSet.v03.IM_EventSetCalc_v3_0_ASCII.main(IM_EventSetCalc_v3_0_ASCII.java:634)
```

**Comment by kevinmilner** [comment]
fixed in c8911da
