### ISSUE TITLE
Issue: Index error in TSA annealing after 5+ hours

### ISSUE THREAD

**Issue by chrisbc** [opensha/opensha#42]
I've run many inversions using the latest TSA classes without any similar issues, but just for the record here's the exception experienced on just one occasion:

This was using the branch opensha/opensha modular-fault-sys-rup-set2

```Threaded total round 17 DONE after 5 hours 40.2 mins, 3,666,509,233 total iterations (179,602 /sec).	13,725/23,675 = 57.97% non-zero rates.
Best energy after 76,180,716 total perturbations:
	Total:	5721366.5 (-0.00%)	Equality:	5721366.5 (-0.00%)	Entropy:	0.0 (NaN)
	Inequality:	0.0 (NaN)	SlipRate:	693829.94 (-0.00%)	RateMinimize:	0.0 (NaN)
	MFDEquality:	5027536.5 (0.00%)	MFDInquality:	0.0 (NaN)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at scratch.UCERF3.simulatedAnnealing.ThreadedSimulatedAnnealing.addScaled(ThreadedSimulatedAnnealing.java:584)
	at scratch.UCERF3.simulatedAnnealing.ThreadedSimulatedAnnealing.iterate(ThreadedSimulatedAnnealing.java:413)
	at scratch.UCERF3.simulatedAnnealing.ThreadedSimulatedAnnealing.iterate(ThreadedSimulatedAnnealing.java:309)
	at nz.cri.gns.NZSHM22.opensha.scripts.FullPipelineDemo.main(FullPipelineDemo.java:257)
```

**Comment by kevinmilner** [comment]
I encountered this error today and think that I fixed it, closing.
